conf_threshold: 0.7

labels:
  bus: 0
  car: 1
  motorbike: 2
  truck: 3

skip_frame: 3

models:
  yolo11:
    path: data/models/best.pt
  detr:
    path: data/models/transformer-based/detr-r50.pt
  faster_rcnn:
    path: data/models/two-stage/faster-rcnn.pt

samples:
  speed_test:
    video_path: data/videos/LLGT_FPT.mp4
    output_path: data/debug/LLGT_FPT.mp4
    annotation_path: data/annotations/LLGT_FPT.yml
  speed_test_1:
    video_path: data/videos/Traffic_VN.mp4
    output_path: data/debug/Traffic_VN.mp4
    annotation_path: data/annotations/Traffic_VN.yml
