labels:
  bus: 0
  car: 1
  motorbike: 2
  truck: 3

frame_skipper:
  target_fps: 60
  max_skip_frames: 6

models:
  yolo11:
    path: api/data/models/one-stage/yolo11-noaugment.pt
    conf_threshold: 0.5
    iou_threshold: 0.5
  rtdetrv2:
    path: api/data/models/transformer-based/rtdetrv2-nano-resnet.pt
    conf_threshold: 0.5
    iou_threshold: 0.5
  faster_rcnn:
    path: api/data/models/two-stage/faster_rcnn.pt
    conf_threshold: 0.5
    iou_threshold: 0.5

samples:
  "1":
    video_path: api/data/samples/videos/cam_1.mp4
    output_path: api/data/debug/videos/cam_1.mp4
    annotation_path: api/data/samples/annotations/cam_1.yml
  "2":
    video_path: api/data/samples/videos/cam_2.mp4
    output_path: api/data/debug/videos/cam_2.mp4
    annotation_path: api/data/samples/annotations/cam_2.yml
  "3":
    video_path: api/data/samples/videos/cam_3.mp4
    output_path: api/data/debug/videos/cam_3.mp4
    annotation_path: api/data/samples/annotations/cam_3.yml
  "4":
    video_path: api/data/samples/videos/cam_4.mp4
    output_path: api/data/debug/videos/cam_4.mp4
    annotation_path: api/data/samples/annotations/cam_4.yml
  "5":
    video_path: api/data/samples/videos/cam_5.mp4
    output_path: api/data/debug/videos/cam_5.mp4
    annotation_path: api/data/samples/annotations/cam_5.yml
