conf_threshold: 0.7

labels:
  bus: 0
  car: 1
  motorbike: 2
  truck: 3

frame_skipper:
  initial_skip: 2
  target_fps: 60
  max_skip_frames: 6
  adjustment_speed: 0.3

models:
  yolo11:
    path: api/data/models/one-stage/yolo11-augdata.pt
  rtdetrv2:
    path: api/data/models/transformer-based/rtdetrv2-nano-resnet.pt
  faster_rcnn:
    path: api/data/models/two-stage/faster_rcnn.pt

samples:
  "1":
    video_path: api/data/samples/videos/LLGT_FPT.mp4
    output_path: api/data/debug/videos/LLGT_FPT.mp4
    annotation_path: api/data/samples/annotations/LLGT_FPT.yml
  "2":
    video_path: api/data/samples/videos/Traffic_VN.mp4
    output_path: api/data/debug/videos/Traffic_VN.mp4
    annotation_path: api/data/samples/annotations/Traffic_VN.yml
